-- MySQL Script generated by MySQL Workbench
-- 08/18/16 18:06:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `cwbusinesservices`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cwbusinesservices`.`ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NAME` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cwbusinesservices`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cwbusinesservices`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `EMAIL` VARCHAR(45) NOT NULL COMMENT '',
  `FIRST_NAME` VARCHAR(45) NULL COMMENT '',
  `LAST_NAME` VARCHAR(45) NULL COMMENT '',
  `PASSWORD` VARCHAR(45) NOT NULL COMMENT '',
  `ACTIVE` TINYINT NULL DEFAULT 1 COMMENT '',
  `ROLE_ID` INT NOT NULL COMMENT '',
  `PHONE` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_USER_TO_ROLE_idx` (`ROLE_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_USER_TO_ROLE`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `cwbusinesservices`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cwbusinesservices`.`PERMISSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cwbusinesservices`.`PERMISSIONS` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NAME` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cwbusinesservices`.`ROLE_PERMISSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cwbusinesservices`.`ROLE_PERMISSIONS` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ROLE_ID` INT NOT NULL COMMENT '',
  `PERMISSION_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_ROLE_TO_PERMISSION_idx` (`PERMISSION_ID` ASC)  COMMENT '',
  INDEX `fk_PERMISSION_TO_ROLE_idx` (`ROLE_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_ROLE_TO_PERMISSION`
    FOREIGN KEY (`PERMISSION_ID`)
    REFERENCES `cwbusinesservices`.`PERMISSIONS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERMISSION_TO_ROLE`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `cwbusinesservices`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into `ROLE` (`NAME`) values ('user');
insert into `ROLE` (`NAME`) values ('moderator');
insert into `ROLE` (`NAME`) values ('admin');

INSERT INTO `PERMISSIONS` (`NAME`) VALUES ('ROLE_USER');
INSERT INTO `PERMISSIONS` (`NAME`) VALUES ('ROLE_MODERATOR');
INSERT INTO `PERMISSIONS` (`NAME`) VALUES ('ROLE_ADMIN');

insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('1', '1');
insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('2', '1');
insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('2', '2');
insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('3', '1');
insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('3', '2');
insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('3', '3');

insert into `USERS` (`EMAIL`, `LAST_NAME`, `PASSWORD`, `ACTIVE`, `ROLE_ID`) VALUES ('admin@cwbusinesservices.com', 'admin', MD5('admin'),1,3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
