INSERT INTO `PERMISSIONS` (`NAME`) VALUES ('CREATE_PLAIN_IMAGE');
INSERT INTO `PERMISSIONS` (`NAME`) VALUES ('DELETE_PLAIN_IMAGE');

insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('3', '57');
insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('3', '58');

insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('2', '57');
insert into `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) values ('2', '58');