package com.cwbusinesservices.pojo.enums;

/**
 * Created by Andrii on 25.07.2017.
 */
public enum PermissionsEnum {
    CREATE_INFO_PAGE,
    EDIT_INFO_PAGE,
    DELETE_INFO_PAGE,
    CREATE_COMPANY,
    DELETE_COMPANY,
    EDIT_COMPANY,
    CREATE_SERVICE,
    EDIT_SERVICE,
    DELETE_SERVICE,
    CREATE_TESTIMONIAL,
    EDIT_TESTIMONIAL,
    DELETE_TESTIMONIAL,
    CREATE_BLOCK,
    EDIT_BLOCK,
    DELETE_BLOCK,
    CREATE_INTEREST,
    EDIT_INTEREST,
    DELETE_INTEREST,
    CREATE_INDUSTRY,
    EDIT_INDUSTRY,
    DELETE_INDUSTRY,
    CREATE_REQUEST,
    EDIT_REQUEST,
    VIEW_REQUEST,
    DELETE_REQUEST,
    CREATE_REQUEST_COMMENT,
    EDIT_REQUEST_COMMENT,
    DELETE_REQUEST_COMMENT,
    STATUS_CHANGE_REQUEST,
    VIEW_REQUEST_COMMENT,
    EDIT_PERMISSIONS_TO_ROLES
}
